Only check for wpa config updates on start

diff --git a/scripts/pirover b/scripts/pirover
--- a/scripts/pirover
+++ b/scripts/pirover
@@ -17,45 +17,6 @@ camera_port=1339
 #################################################
 
 # Update wpa_supplicant.conf with any new wifi networks
-wpa_config_update
-
-#################################################
-
-bin_dir="/usr/local/bin"
-log_dir="/var/log"
-
-declare -A processes=(
-	["controller"]="--port=$controller_port"
-	["camera"]="--port=$camera_port"
-	["broadcast"]="--port=$broadcast_port --ctrlport=$controller_port --camport=$camera_port"
-	["lights"]=""
-)
-
-if [ "$1" = "start" ]
-then
-	log_redir=$([ "$logging" == true ] && echo "&>$log_dir/$(date +"%d_%m_%y-%T").txt" || echo "")
-
-	for process in "${!processes[@]}"
-	do
-		eval "$bin_dir/$process $log_redir ${processes[$process]} &"
-	done
-elif [ "$1" = "stop" ]
-then
-	for process in "${!processes[@]}"
-	do
-		pid=$(pidof "$process")
-		if [ "$pid" -eq "$pid" ] 2>/dev/null # If is an actual PID
-		then
-			echo "Stopping $process"
-			kill -9 "$pid"
-		else
-			echo "$process is not running"
-		fi
-	done
-else
-    echo "Invalid command"
-fi
-
 function wpa_config_update {
     new_conf=/boot/wpa.conf
     conf=/etc/wpa_supplicant/wpa_supplicant.conf
@@ -78,3 +39,44 @@ function wpa_config_update {
         echo "No new wpa_supplicant.conf info."
     fi
 }
+
+#################################################
+
+# Start/Stop processes
+bin_dir="/usr/local/bin"
+log_dir="/var/log"
+
+declare -A processes=(
+	["controller"]="--port=$controller_port"
+	["camera"]="--port=$camera_port"
+	["broadcast"]="--port=$broadcast_port --ctrlport=$controller_port --camport=$camera_port"
+	["lights"]=""
+)
+
+if [ "$1" = "start" ]
+then
+    # Check for updates on start
+    wpa_config_update
+
+	log_redir=$([ "$logging" == true ] && echo "&>$log_dir/$(date +"%d_%m_%y-%T").txt" || echo "")
+
+	for process in "${!processes[@]}"
+	do
+		eval "$bin_dir/$process $log_redir ${processes[$process]} &"
+	done
+elif [ "$1" = "stop" ]
+then
+	for process in "${!processes[@]}"
+	do
+		pid=$(pidof "$process")
+		if [ "$pid" -eq "$pid" ] 2>/dev/null # If is an actual PID
+		then
+			echo "Stopping $process"
+			kill -9 "$pid"
+		else
+			echo "$process is not running"
+		fi
+	done
+else
+    echo "Invalid command"
+fi
